Добавил 7 задание
FO2XS/Collective-IT-Development pull request #11
Opened 2021-05-31 12:57 UTC by ArGoNArGoN

2021-06-03 10:51 UTC, FO2XS requested changes
Все работает, есть небольшие огрехи. Комментарии оставил

2021-06-03 10:51 UTC, FO2XS commented on Laba7/main.py
> +doc = bs(codecs.open('C:/Users/Qwerty/Downloads/Сериал Рик и Морти 1-4 сезон 1-10 серия смотреть онлайн в хорошем качестве.html', encoding='utf-8', mode='r').read(), 'html.parser')
Добавь сам файл для парсинга и поменяй абсолютный путь на относительный

2021-06-03 10:51 UTC, FO2XS commented on Laba7/main.py
> +print('Название:', name)
Вывод названия происходит вместе с html-разметкой. Выглядит ужасно, нужно поправить
Стоит ли выводить полное описание, если мы хотим вывести только название?
![image](https://user-images.githubusercontent.com/74563717/120631366-78fa8f80-c470-11eb-89c7-5d5bebb13b15.png)

2021-06-03 10:51 UTC, FO2XS commented on Laba7/main.py
> +print('Количество положительных отзывов:', count)
Ты используешь переменную count только в одном месте, можно вставить вызов функции напрямую в print по типу:
![image](https://user-images.githubusercontent.com/74563717/120632322-7fd5d200-c471-11eb-9189-991d8cba298a.png)
или, если длинные строки раздражают
![image](https://user-images.githubusercontent.com/74563717/120632372-8fedb180-c471-11eb-911d-a60ac2270c20.png)

и это не усложнит читабельность кода

2021-06-03 10:51 UTC, FO2XS commented on Laba7/main.py
> +print('Количество отрицательных отзывов:', count)
см. выше

2021-06-03 10:51 UTC, FO2XS commented on Laba7/main.py
> +print('Описание:', text)
Аналогично с count

2021-06-03 10:51 UTC, FO2XS commented on Laba7/main.py
> +    rating = int(node.select('.ratingtypeplusminus')[0].get_text());
=> ; <=

2021-06-03 10:51 UTC, FO2XS commented on Laba7/main.py
> +    a = node.find_all(['a']);
=> ; <= x2
И зачем тебе вообще нужна переменная "a"? Ведь ты её не используешь

2021-06-03 10:51 UTC, FO2XS commented on Laba7/main.py
> +    print("парень с ником '", author, "' написал:", message, "рэйтинг", rating, "\n\n")
"парень с ником". А если я девушка, мужчина ставший девушкой или гендерфлюидный вертосексуал. Давай заменим на "человек"

2021-06-04 18:49 UTC, FO2XS approved these changes

2021-06-07 15:48 UTC, stanislavlyalin requested changes

2021-06-07 15:48 UTC, stanislavlyalin commented on 9 lab/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Комментарий относится ко всему pull request:

Слишком большое количество файлов пытаетесь влить в этом pull request. Некоторые из них - служебные файлы PyCharm, которые следует добавить в `.gitignore`, а не хранить в репозитории. JavaScript и картинки из веб-страницы тоже не нужны, т.к. они не имеют отношения к парсингу. Их можно просто удалить из репозитория. Тогда pull request станет намного чище

2021-06-08 03:01 UTC, merged