Добавил 8 задание
FO2XS/Collective-IT-Development pull request #12
Opened 2021-05-31 13:02 UTC by ArGoNArGoN

2021-06-03 15:32 UTC, FO2XS requested changes
Выражения написаны отлично. Со своей стороны предлагаю только дополнить их (в комментариях все расписал)

2021-06-03 15:32 UTC, FO2XS commented on Laba8/main.py
> +result = re.findall(r'#[0-9A-F]{3,6}', str)
![image](https://user-images.githubusercontent.com/74563717/120664877-f8e62100-c493-11eb-859f-e705e42d9b9a.png)
В случае, если код цвета содержит больше 6 символов (см. скрин), то регулярка выделяет первые 6 символов.
![image](https://user-images.githubusercontent.com/74563717/120665195-3c408f80-c494-11eb-8c30-ae8c0dd1f6f1.png)
Но правильно ли считать, что это код цвета?

2021-06-03 15:32 UTC, FO2XS commented on Laba8/main.py
> +print();
=>;<=

2021-06-03 15:32 UTC, FO2XS commented on Laba8/main.py
> +print();
=>;<= x2

2021-06-03 15:32 UTC, FO2XS commented on Laba8/main.py
> +result = re.findall(r'http(s:|:)//([a-z]*.[a-z]*)/', str)
![image](https://user-images.githubusercontent.com/74563717/120669444-21701a00-c498-11eb-9ae8-53a50ff7aed0.png)
В доменах могут встречаться цифры, кроме доменов верхнего уровня (посмотрел список, там ни одной цифры не встретилось)
Дополни регулярку, чтобы она сработала на домене типа 123134.ru

2021-06-03 15:32 UTC, FO2XS commented on Laba8/main.py
> +    print(i[1]);
=>;<= x3

2021-06-03 15:32 UTC, FO2XS commented on Laba8/main.py
> +print();
=>;<= x4

2021-06-03 15:32 UTC, FO2XS commented on Laba8/main.py
> +print();
=>;<= x5

2021-06-04 14:17 UTC, FO2XS commented on Laba8/main.py
> +result = re.findall(r'http(s:|:)//([a-z|0-9]*.[a-z|0-9]*)/', str)
В доменах верхнего уровня нет цифр, я же написал об этом ранее, только в нижестоящих

2021-06-04 17:00 UTC, ArGoNArGoN commented on Laba8/main.py
> +result = re.findall(r'#[0-9A-F]{3,6}', str)
я думаю, что да.
Ибо нужно было программу, которая будет выявлять код цвета.

2021-06-04 17:37 UTC, FO2XS approved these changes
С моей стороны все гуд

2021-06-07 15:53 UTC, stanislavlyalin requested changes

2021-06-07 15:53 UTC, stanislavlyalin commented on 9 lab/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Служебные файлы .idea - в .gitignore

2021-06-07 15:53 UTC, stanislavlyalin commented on Laba8/main.py
> +print(re.findall(r'#[0-9A-z]{3,6}', str))
`{3,6}` означает от 3 до 6 включительно, т.е. и 4, и 5 входят. Нужно строго либо 3, либо 6

2021-06-07 15:53 UTC, stanislavlyalin commented on Laba8/main.py
> +result = re.findall(r'http(s:|:)//([a-z|0-9]*.[a-z]*)/', str)
* Буквы любого регистра допустимы
* Вместо `*` лучше `+`, т.к. хотя бы одно вхождение символа должно быть
* Точку нужно экранировать, иначе это означает любой символ

2021-06-07 15:53 UTC, stanislavlyalin commented on Laba8/main.py
> +    result = re.findall(r'^([a-z]*.(png|jpeg|gif|jpg))', i)
* В имени файла могут быть дефисы (`-`), подчёркивания (`_`), цифры
* Вместо `*` лучше `+`
* Точку нужно экранировать

2021-06-09 02:53 UTC, merged