Добавил 9 задание
FO2XS/Collective-IT-Development pull request #13
Opened 2021-05-31 13:04 UTC by ArGoNArGoN

9 Lab - первое задание
9 Lab2 -  второе задание

2021-06-03 16:10 UTC, FO2XS requested changes
Обе программы работоспособны. Для 7 варианта все отлично, 1 вариант нужно сделать с реализацией перечислений (см. комментарий)

2021-06-03 16:10 UTC, FO2XS commented on 9 lab/main.py
> +        self.patch = QFileDialog.getOpenFileNames(self, "C:\\Users", "C:\\Users", "'PNG Image (*.png)'")[0][0]
Все написано хорошо, разве что поменяй путь на корневой путь диска C и вставь условное "имя" файла, чтобы было понятно, что надо загрузить картинку

2021-06-03 16:10 UTC, FO2XS commented on 9 lab2/main.py
> +class Operation:
Перепиши используя, перечисление 
![image](https://user-images.githubusercontent.com/74563717/120676765-09e85f80-c49f-11eb-85ae-786830bb9c83.png)
Команда импорта перечислений: from enum import Enum

2021-06-04 18:49 UTC, FO2XS approved these changes

2021-06-07 15:56 UTC, stanislavlyalin requested changes

2021-06-07 15:56 UTC, stanislavlyalin commented on 9 lab/.idea/.gitignore
> +# Default ignored files
Все файлы из `.idea` - в игнор

2021-06-07 15:56 UTC, stanislavlyalin commented on 9 lab2/main.py
> +main2()
Лучше так:
```python
if __name__ == '__main__':
    main2()
```

2021-06-08 03:04 UTC, merged