Завершенная работа по k-means
FO2XS/Collective-IT-Development pull request #5
Opened 2021-03-19 20:00 UTC by FO2XS

В соответствии с заданием лабы, код в нужных частях дописан и полностью работает

2021-03-20 07:34 UTC, stanislavlyalin requested changes

2021-03-20 07:34 UTC, stanislavlyalin commented on Laba3/k_means.py
> +def dist(A, B):
Реализуйте с использованием библиотеки `numpy` в одну строку кода.

2021-03-20 07:34 UTC, stanislavlyalin commented on Laba3/k_means.py
> +    distances = np.zeros((m, k))
Используя [генераторы списков в Python](https://younglinux.info/python/feature/generators) строки 24-27 нужно объединить в одну. При этом вложенных циклов может быть сколько угодно. В вашем случае их будет 2.

2021-03-20 07:34 UTC, stanislavlyalin commented on Laba3/k_means.py
> +            centers[i][j] = np.random.uniform(Mini[i], Maxi[i])
Проверьте, что функция `uniform` может возвращать сразу матрицу нужного размера. Тогда 2 вложенных цикла будут не нужны, и хватит одного вызова функции

2021-03-20 07:34 UTC, stanislavlyalin commented on Laba3/k_means.py
> +        if np.all(prev_iteration == curr_iteration):
Условие выхода из цикла лучше поместить рядом с `while`, чтобы код был более читаемым

2021-04-08 21:31 UTC, FO2XS commented on Laba3/k_means.py
> +def dist(A, B):
Реализовано, коммит внёс

2021-04-08 22:04 UTC, FO2XS reviewed
I maked fixes

2021-04-08 22:04 UTC, FO2XS commented on Laba3/k_means.py
> +    distances = np.zeros((m, k))
Интересный подход, правда голова ломается при попытке чтения. Сделал, commit did

2021-04-08 22:04 UTC, FO2XS commented on Laba3/k_means.py
> +            centers[i][j] = np.random.uniform(Mini[i], Maxi[i])
Да, действительно был параметр для размеров возвращаемой матрицы, убрал лишние циклы. Закоммитил

2021-04-08 22:04 UTC, FO2XS commented on Laba3/k_means.py
> +        if np.all(prev_iteration == curr_iteration):
Поменял all на any и вставил вместо True

2021-04-08 22:06 UTC, FO2XS commented
Мне интересно, а я могу свои исправленные блока кода вносить под комментарии учителя?

2021-04-11 19:04 UTC, merged