2LabIsReady
FO2XS/Collective-IT-Development pull request #6
Opened 2021-03-19 20:01 UTC by ArGoNArGoN

Выполнил 2 лаб. работу

2021-03-19 20:05 UTC, FO2XS approved these changes
Все написано хорошо. Вообще мы вместе это сделали, конечно, я знаю, что это работает. Лол.

2021-03-20 07:30 UTC, stanislavlyalin requested changes

2021-03-20 07:30 UTC, stanislavlyalin commented on Laba2/Tasks.py
> +    return s
Функция очень простая, для компактности можно записать в одну строку:
```python
return ''.join(sorted(list(s)))
```

2021-03-20 07:30 UTC, stanislavlyalin commented on Laba2/Tasks.py
> +def FiboCalc(prev, curr, count):
Можно сделать проще. Посмотрите [здесь](https://younglinux.info/algorithm/fibonacci). В функцию достаточно передать один аргумент. Промежуточные результаты можно не выводить на экран. Если хотите выводить последовательность чисел Фибоначчи, можете написать цикл, в котором вызывать рекурсивную функцию `FiboCalc`. Проверяйте также, что аргумент функции имеет тип `int`:
```python
type(n) == int
```

2021-05-31 12:46 UTC, closed without merging