Laba6
FO2XS/Collective-IT-Development pull request #8
Opened 2021-04-11 00:18 UTC by FO2XS

Laba 6 complete

2021-04-11 19:16 UTC, stanislavlyalin requested changes

2021-04-11 19:16 UTC, stanislavlyalin commented on Laba6/start.py
> +from PIL import Image
Бинарные данные (картинки .png) лучше не хранить в репозитории. Удалите их

2021-04-11 19:16 UTC, stanislavlyalin commented on Laba6/start.py
> +X = np.array([x, x ** 2.0, x**3.0, x**4.0]).transpose()
Добавьте функцию, которая принимает 2 параметра: ширину изображения и степень полинома, и возвращает матрицу `X`

2021-04-11 19:16 UTC, stanislavlyalin commented on Laba6/start.py
> +
Добавьте [`enum`](https://docs.python.org/3/library/enum.html) для цветовых каналов:
```python
from enum import Enum
class Color(Enum):
	RED = 0
	GREEN = 1
	BLUE = 2
```

2021-04-11 19:16 UTC, stanislavlyalin commented on Laba6/start.py
> +R = data[0, :, 0]
С использованием `enum` код можно преобразовать:
```python
R = data[0, :, Color.RED.value]
...
```

2021-04-11 19:16 UTC, stanislavlyalin commented on Laba6/start.py
> +lm.fit(X, R)
Добавьте функцию `predict_for_channel`, которая принимает матрицу `X` и значение `enum` и возвращает предсказание для цветового канала:
```python
Rpredicted = predict_for_channel(X, Color.RED)
```

2021-04-11 19:16 UTC, stanislavlyalin commented on Laba6/start.py
> +    lm.fit(X, R)
Используйте объявленную выше функцию `predict_for_channel`

2021-04-11 19:16 UTC, stanislavlyalin commented on Laba6/start.py
> +    diff = R - Rpredicted
Дублирующийся код. Лучше тоже вынести в функцию

2021-04-11 19:16 UTC, stanislavlyalin commented on Laba6/start.py
> +for i in range(im.height):
Код для генерации картинки лучше вынести в отдельную функцию. Пусть она принимает имя входного файла, имя выходного файла, количество бит для кодирования (по умолчанию = 5).

2021-04-12 21:01 UTC, FO2XS reviewed
Вынес обработку изображения в отдельную функцию, принимающую следующие параметры: имена входного и выходного файла, количество бит для кодирования и степень полинома. Для предсказания RGB цветов и обрезки выходящих из диапазона значений созданы отдельные функции. Удалил из репозитория png файлы

2021-04-12 21:01 UTC, FO2XS commented on Laba6/start.py
> +from PIL import Image
Удалил

2021-04-12 21:01 UTC, FO2XS commented on Laba6/start.py
> +X = np.array([x, x ** 2.0, x**3.0, x**4.0]).transpose()
Сделал

2021-04-12 21:01 UTC, FO2XS commented on Laba6/start.py
> +
complete

2021-04-13 03:40 UTC, merged